targetX = 0
targetY = 0
target_room = 0;
target_face = 0;
locked = false;
conditional = true;
msg = ["Doesn't seem like you can go in here."];
isDialogue = false;
hasTriggered = false;
hasDialogue = true;